### ISSUE TITLE
Error in backend after installation with composer

### ISSUE THREAD

**Issue by oim37** [dimsog/wn-comments-plugin#9]
Hello,

I use last winter cms 1.2.2 (PHP 8.0.29) and after installation in admin (backend) have error:

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'winter.dimsog_comments' doesn't exist in /var/www/vhosts/domain.tld/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82

After checking the structure of the database table is not present. Why it was not created during installation, how to fix it?

**Comment by LukeTowers** [comment]
@oim37 how did you install it? If you installed via composer you still have to run `artisan migrate`
